### ISSUE TITLE
"New achievement" modal displaying for other users

### ISSUE THREAD

**Issue by JanderV** [malago86/flarum-achievements#13]
First of all, thanks for making this awesome plugin! :)

I did notice other users could get the "New achievement" modal that's actually meant for someone else when you visit someone's profile page. 

**steps to reproduce it**
1. User A gets an achievement but doesn't dismiss the modal.
2. User B visits the profile page of user A.
3. The modal will keep popping up for user B every time he visits user A's profile until user A actually clicks dismisses the modal.

**Comment by malago86** [comment]
I am trying to reproduce the bug but I can't!

I created a new user, got an achievement and while the modal is there, on another window with a different user I got to the first user's profile but it does not show any modal for me. I tried both adding an achievement manually and with a trigger (1 like).

What achievement trigger are you using?

**Comment by JanderV** [comment]
Oh this is weird, I tested it multiple times yesterday and the problem was very consistent.
I did reset the forum in the meantime, and now I can't seem to reproduce it either.

Maybe the bug happened due to another plugin I installed, or maybe a certain configuration?
I guess for now it somehow solved itself :) 
I'll let you know if I run into it again and can pinpoint it better.

Thanks for your help.

**Comment by malago86** [comment]
Interesting... I have no idea how you triggered it, but if you find out, please reopen this issue!

**Comment by JanderV** [comment]
We've run into the same problem again.
It seems the missing key element was that both users need to have gotten the same achievement.

So the steps to reproduce should be as follows:

1. User A and B get the same achievement.
2. **Only** user B dismisses the "new achievement" model.
3. User B then visits the profile page of user A.
4. The modal will keep popping up for user B every time he visits user A's profile until user A actually dismisses the modal.

This seems to happen for both; **manual** and **automatic** achievements. 

However for **manual** achievements the bug also seems to occur in topics that the other user has posted in (so also when user B visits a topic where user A has posted).

**Comment by malago86** [comment]
I believe I fixed this issue (probably a few more at the same time). Please update to 0.4.3 and let me know if it does not work!

**Comment by JanderV** [comment]
It works! Thanks! 😄
