### ISSUE TITLE
[BUG]in console log

### ISSUE THREAD

**Issue by justoverclockl** [malago86/flarum-achievements#14]
Actually i have this error on console log, i'm opening the issue here so its easy to track:

![Immagine 2021-04-20 175027](https://user-images.githubusercontent.com/79002016/115426579-ecb64500-a200-11eb-89d0-4e3884cb826c.png)

**Comment by malago86** [comment]
This has been fixed thanks to @askvortsov1 on commit #15 

Update to version 0.2.7
