### ISSUE TITLE
Badge is not showing properly on the post in the user page

### ISSUE THREAD

**Issue by itzfatoni** [malago86/flarum-achievements#17]
I am trying to use image for badge instead of FA. The badge is showing properly on the post in discussion page. (https://domain.com/d/...) But when i see the post from the user page the badge seem overflow. (https://domain.com/u/...)

Flarum-achievement 0.3.1
image height 96
image width 96
row 1
column 1

**Comment by malago86** [comment]
This has been fixed on version 0.4.0, thanks for your report!
