### ISSUE TITLE
Conflict with the-turk/flarum-diff

### ISSUE THREAD

**Issue by xasha32** [malago86/flarum-achievements#18]
IF we enable `malago/flarum-achievements` and `the-turk/flarum-diff`  The edit history button doesn't work 

Error video link - https://youtu.be/dJrfEmld0sA

Browser console error image link - https://telegra.ph/file/1d4c96c7a269ff8428f0a.png

**Comment by malago86** [comment]
Thanks for your report, please try the updated version 0.4.2, it should fix this issue.
