### ISSUE TITLE
[Enhancement] Different Achievement Image Sizes for Achievement Modal and Posts

### ISSUE THREAD

**Issue by Ralkage** [malago86/flarum-achievements#2]
As originally brought up here https://discuss.flarum.org/d/26675-flarum-achievements-reward-your-users-for-participating/26, it would be nice to have configurable size options for achievements displayed in both the Achievement modal and posts themselves. This will make it look a bit like how Reddit and most platforms have it and it honestly looks so much more modern.

<details>
<summary>Reddit award modal:</summary>

![Reddit award modal](https://i.imgur.com/2Kv2eH5.png)
</details>

<details>
<summary>The post awards (count not required):</summary>

>! ![Reddit post awards](https://i.imgur.com/Hz3xIJh.png)
</details>

**Comment by malago86** [comment]
In the last version, you can use font awesome icons as achievements, this looks more like what you are looking for:

![image](https://i.imgur.com/4Tc0SDg.png)
</details>

![image](https://i.imgur.com/o2dLIF1.png)
</details>

Right now, for both images and icons, the new achievement modal shows the image/icon at twice the size as in the achievement list on each post.
