### ISSUE TITLE
translation missed

### ISSUE THREAD

**Issue by justoverclockl** [malago86/flarum-achievements#20]
![ff](https://user-images.githubusercontent.com/79002016/129423526-9811ca75-52f2-4290-86f0-d9a0d540c01d.png)

the save buttons is without translation

**Comment by justoverclockl** [comment]
there are also lot of issues mentioned here:
https://discuss.flarum.org/d/26675-flarum-achievements-reward-your-users-for-participating/156

**Comment by malago86** [comment]
> there are also lot of issues mentioned here:
> https://discuss.flarum.org/d/26675-flarum-achievements-reward-your-users-for-participating/156

Let's fix this first. I don't see any error on my console. **Did you try to clear the cache after updating?** Does it only show with version 0.5 or also with 0.4.3?

**Comment by justoverclockl** [comment]
With last version I can’t see any achievements and lot of error. Yes cache cleared

**Comment by malago86** [comment]
I can't reproduce this error. Can you try on a local installation with no other extensions? Is it possible that an update on another extension caused this?

I tried both locally and on my forum and I can't see any errors, I will keep trying... 🤔

**Comment by justoverclockl** [comment]
The error stops when I’ve reverted your ext to 0.3.1 (that works fine). I will try on a local install

**Comment by justoverclockl** [comment]
on a local install apparently works, so its a conflict maybe with another extension, but i get error on console


Uncaught (in promise) SyntaxError: Unexpected token o in JSON at position 1
    at JSON.parse (<anonymous>)
    at index.js:122
