### ISSUE TITLE
How can I DEL an Achievement

### ISSUE THREAD

**Issue by SeimoDev** [malago86/flarum-achievements#21]
Is there any way allow me to delete an achievement or edit it?

**Comment by malago86** [comment]
You can do this on the admin page. Just click on the achievement icon and it will bring up the edit popup. You can edit or delete them there.

**Comment by SeimoDev** [comment]
No,I don't think I can do it,if I click on the achievement icon,I just can add a user,maybe it's because of the achievement setting?

**Comment by malago86** [comment]
Like this:
![image](https://i.ibb.co/b5wTsMK/smyh-Re-SWvd.gif)

If nothing opens when you click on the achievement icon, can you check the javascript console errors on your browser. You can open this panel pressing F12 and going to the Console tab. If there is some red text there, please copy it here so I can check it.

**Comment by SeimoDev** [comment]
I got it
but why there no icon on the achievement 
![image](https://user-images.githubusercontent.com/43766162/131234577-242e41a9-99c9-4bae-9a68-059b8b5607d4.png)

**Comment by malago86** [comment]
You need to add an icon to each achievement. You can do this as a fontawesome icon or using your own image. Check the [examples here](https://github.com/malago86/flarum-achievements/blob/main/README.md).
