### ISSUE TITLE
A bug was found on the user profile page, which caused the page to fail to load normally.

### ISSUE THREAD

**Issue by huasio** [malago86/flarum-achievements#22]
This problem occurs when a guest who is not logged in tries to access a user's personal homepage.

![image](https://user-images.githubusercontent.com/23445537/139524035-658cee2f-5f82-4feb-b5cc-dc7b5f000a0b.png)

**Comment by malago86** [comment]
It looks like something broke after Flarum 1.1.1, I will check this asap.

**Comment by malago86** [comment]
Update to 0.5.1 and let me know if the issue is solved!

`composer update malago/flarum-achievements`

**Comment by huasio** [comment]
> Update to 0.5.1 and let me know if the issue is solved!
> 
> `composer update malago/flarum-achievements`

It seems that through this command, it is not possible to update to 0.5.1?

![image](https://user-images.githubusercontent.com/23445537/140008472-7ee16369-a339-40e9-85a2-e61436b2f52d.png)
