### ISSUE TITLE
Invalid description for "Average words" variable?

### ISSUE THREAD

**Issue by rob006** [malago86/flarum-achievements#24]
https://github.com/malago86/flarum-achievements/blob/438c21fd160c030bdbcd627f32a944c774426bff/locale/en.yml#L67

This does not look correct. From my understanding this variable uses average number of words in post to calculate achievement conditions. There is no word search in query used for this achievement: 

https://github.com/malago86/flarum-achievements/blob/b4019367df2be08cd350699e17481e90ff6ea830/src/Listeners/UpdateAchievementsOnPost.php#L32

**Comment by malago86** [comment]
You are right! Thanks for bringing this up, I fixed it and updated the version number: https://github.com/malago86/flarum-achievements/commit/3272cb3a920115d501e5dcff5add084f07be8631
