### ISSUE TITLE
[Enhancement] Add Helper Text to Configurable Options

### ISSUE THREAD

**Issue by Ralkage** [malago86/flarum-achievements#3]
As noted here https://discuss.flarum.org/d/26675-flarum-achievements-reward-your-users-for-participating/25, there is some confusion to how most of the options in this extension work and what values should be set. We should add helper text to these options to help those confused about what each one does specifically and what values should be set. I would suggest making the modal a bit wider so that users don't have to scroll very far to submit any changes or create new achievements.

<details>
<summary>Configure Achievement Modal:</summary>

![image](https://user-images.githubusercontent.com/2059356/113466198-cd997400-9407-11eb-9aab-78d9cedc2027.png)
</details>

**Comment by malago86** [comment]
I have added two examples to the [README file](https://github.com/malago86/flarum-achievements/blob/main/README.md), one with a custom image, and another one with a font awesome icon.

I will study other options if this is still confusing!

**Comment by Ralkage** [comment]
I finally realized that the helper text/instructions were on the Admin page lol 🤦‍♂️

What this FR aims to achieve is to move those instructions to the Achievement creation model as helper text under each associating label and make the model a bit wider so it doesn't look cramped after the change.

**Comment by malago86** [comment]
Version 0.3.0 #5  adds a tooltip on the variable field that helps knowing what kind of values you can add.
