### ISSUE TITLE
[Enhancement] Add "achievements" page in sidebar

### ISSUE THREAD

**Issue by justoverclockl** [malago86/flarum-achievements#5]
could be awesome to have an "achievements" page on the sidebar, that show all the available achievements that a user could reach.

**Comment by malago86** [comment]
Yes, that is absolutely one of my next steps for the extension! Also a list of your own achievements in the profile section might be cool.

I also want to make some achievements _hidden_ to make them more like a suprise so that is another feature I want to add in the future.

**Comment by malago86** [comment]
This has been added on version 0.3.0 #16
