### ISSUE TITLE
Console log

### ISSUE THREAD

**Issue by justoverclockl** [malago86/flarum-achievements#8]
![Immagine 2021-04-08 165319](https://user-images.githubusercontent.com/79002016/114048584-006dbd00-988b-11eb-95ca-1e6b9fefa8ae.png)

Can u remove also the log? (if is a log)

**Comment by malago86** [comment]
I removed it on 0.2.3, is it still showing? There is no more logs in the code:

https://github.com/malago86/flarum-achievements/search?q=console.log

Maybe deleting the cache helps?

**Comment by justoverclockl** [comment]
these are the image for my achievements

![Immagine 2021-04-08 190614](https://user-images.githubusercontent.com/79002016/114067891-9a3e6580-989d-11eb-8ae3-71c003a5a4a0.png)

yes, a lot, cache cleared but they still there

**Comment by malago86** [comment]
Got the update!

### 0.2.5

- Removed JS log
- Fixed calculation for comments on discussion achievements

This should solve this issue.
